
CREATE TABLE SyncState  (
  key TEXT NOT NULL PRIMARY KEY,
  state JSON NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER SyncStateUpdated
AFTER UPDATE ON SyncState
BEGIN
  UPDATE SyncState SET updatedAt = CURRENT_TIMESTAMP WHERE key = NEW.key;
END;
