import Fs from 'node:fs/promises';
import Path from 'node:path';
import * as ts from 'typescript';
import { format, resolveConfig } from 'prettier';
import { createNativeTypeTranslator } from './generation/nativeTypes.js';
import { readRuntimeSource } from './generation/readRuntimeSource.js';
import type { RuntimeTypeOverrides } from './typeOverrides.js';

const outputPath = Path.join(import.meta.dirname, 'HistoricalEvents.generated.ts');
const npmPackage = '@argonprotocol/mainchain';
const rootPackageJsonPath = Path.resolve(import.meta.dirname, '../../package.json');
const runtimeSourcesPath = Path.resolve(import.meta.dirname, 'history/RuntimeSources.json');
const typeOverridesPath = Path.resolve(import.meta.dirname, '../../runtime-type-overrides.json');
const sources = JSON.parse(
  process.env.ARGON_RUNTIME_SOURCES ?? (await Fs.readFile(runtimeSourcesPath, 'utf8')),
) as Record<number, string[]>;
const typeOverrides = JSON.parse(await Fs.readFile(typeOverridesPath, 'utf8')) as RuntimeTypeOverrides;

type EventFields = Record<string, string>;
type EventChanges = { spec: number; section: string; method: string; fields: EventFields | null }[];
type NativeEventDeclaration = { section: string; method: string; fields: EventFields };
type SourceDeclarations = {
  events: Record<string, Record<string, { codecFields: EventFields; nativeFields: EventFields }>>;
};

await verifyPinnedRuntimeSource();

const changes: EventChanges = [];
const sourceLabels: Record<number, string> = {};
const nativeEventDeclarations = new Map<string, NativeEventDeclaration>();
let previousDeclarations: Record<string, Record<string, EventFields[]>> = {};

for (const [rawSpecVersion, sourceVersions] of Object.entries(sources)) {
  const specVersion = Number(rawSpecVersion);
  sourceLabels[specVersion] = sourceVersions
    .map(source => (source.startsWith('argonprotocol/') ? source : `${npmPackage}@${source}`))
    .join(', ');

  const declarationsForSpec: Record<string, Record<string, EventFields[]>> = {};
  const declarationsAtSpec = await Promise.all(sourceVersions.map(readSourceDeclarations));
  for (const sourceDeclarations of declarationsAtSpec) {
    for (const [section, methods] of Object.entries(sourceDeclarations.events)) {
      for (const [method, { codecFields, nativeFields }] of Object.entries(methods)) {
        const alternatives = ((declarationsForSpec[section] ??= {})[method] ??= []);
        if (!alternatives.some(candidate => JSON.stringify(candidate) === JSON.stringify(codecFields))) {
          alternatives.push(codecFields);
        }

        const nativeDeclaration = { section, method, fields: nativeFields };
        nativeEventDeclarations.set(JSON.stringify(nativeDeclaration), nativeDeclaration);
      }
    }
  }

  const sections = new Set([...Object.keys(previousDeclarations), ...Object.keys(declarationsForSpec)]);
  for (const section of sections) {
    const previousMethods = previousDeclarations[section] ?? {};
    const currentMethods = declarationsForSpec[section] ?? {};
    const methods = new Set([...Object.keys(previousMethods), ...Object.keys(currentMethods)]);

    for (const method of methods) {
      const previousAlternatives = previousMethods[method] ?? [];
      const currentAlternatives = currentMethods[method] ?? [];
      if (JSON.stringify(previousAlternatives) === JSON.stringify(currentAlternatives)) continue;

      if (!currentAlternatives.length) {
        changes.push({ spec: specVersion, section, method, fields: null });
      } else {
        for (const fields of currentAlternatives) changes.push({ spec: specVersion, section, method, fields });
      }
    }
  }
  previousDeclarations = declarationsForSpec;
}

const header = `// Generated by \`yarn workspace @argonprotocol/runtime-client generate\`.
// Sources are immutable published @argonprotocol/mainchain packages, except spec 124,
// which was not published separately and is read from its fixed mainchain commit.
// A spec emits only event tuples changed from the preceding spec. Null fields remove an event.

`;
const declarationsByEvent = new Map<string, NativeEventDeclaration[]>();
for (const declaration of nativeEventDeclarations.values()) {
  const key = `${declaration.section}.${declaration.method}`;
  const declarations = declarationsByEvent.get(key) ?? [];
  declarations.push(declaration);
  declarationsByEvent.set(key, declarations);
}

const eventDataTypes: string[] = [];
const eventTypes: string[] = [];
for (const declarations of [...declarationsByEvent.values()].sort(([left], [right]) => {
  return left.section.localeCompare(right.section) || left.method.localeCompare(right.method);
})) {
  const { section, method } = declarations[0];
  const dataTypeName = `Historical${pascalCase(section)}${pascalCase(method)}EventData`;
  const fieldVariants = declarations.map(({ fields }) => renderNativeFields(fields));
  const dataType = fieldVariants.length === 1 ? fieldVariants[0] : `MergeHistorical<${fieldVariants.join(' | ')}>`;
  eventDataTypes.push(`type ${dataTypeName} = ${dataType};`);
  eventTypes.push(
    `  | { readonly section: ${JSON.stringify(section)}; readonly method: ${JSON.stringify(method)}; readonly data: ${dataTypeName} }`,
  );
}

const eventDataOutput = eventDataTypes.join('\n\n');
const output = `${header}${eventDataOutput.includes('BigNumber') ? "import type BigNumber from 'bignumber.js';\n" : ''}import type { MergeHistorical } from './client.js';

${eventDataOutput}

export type HistoricalEvent =
${eventTypes.join('\n')};

export const historicalEventSpecSources = ${JSON.stringify(sourceLabels)} as const;

export const historicalEventChanges = ${JSON.stringify(changes)} as const;
`;
const prettierConfig = await resolveConfig(outputPath);
const formattedOutput = await format(output, { ...prettierConfig, parser: 'typescript' });
if (process.argv.includes('--check')) {
  const currentOutput = await Fs.readFile(outputPath, 'utf8');
  if (currentOutput !== formattedOutput) {
    throw new Error('HistoricalEvents.generated.ts is out of date; run the runtime client generator');
  }
} else {
  await Fs.writeFile(outputPath, formattedOutput);
}

async function verifyPinnedRuntimeSource(): Promise<void> {
  const packageJson = JSON.parse(await Fs.readFile(rootPackageJsonPath, 'utf8')) as {
    resolutions?: Record<string, string>;
  };
  const pinnedVersion = packageJson.resolutions?.[npmPackage];
  if (!pinnedVersion) throw new Error(`${npmPackage} is missing from package.json resolutions`);
  if (pinnedVersion.startsWith('portal:')) return;

  const isRegistered = Object.values(sources).some(sourceVersions => {
    return sourceVersions.some(source => source === pinnedVersion);
  });
  if (!isRegistered) {
    throw new Error(
      `${npmPackage}@${pinnedVersion} is not registered in this generator's runtime sources. ` +
        'Add its runtime spec mapping and disposition every structural event change.',
    );
  }
}

async function readSourceDeclarations(source: string): Promise<SourceDeclarations> {
  const contents = await readRuntimeSource(source);
  const sourceFile = ts.createSourceFile('augment-api-events.ts', contents.eventSource, ts.ScriptTarget.Latest, true);
  const eventsInterface = findEventsInterface(sourceFile);
  if (!eventsInterface) throw new Error(`Unable to find AugmentedEvents in ${source}`);
  const translator = createNativeTypeTranslator(contents.lookupSource, typeOverrides.fields, contents.definitionSource);

  const result: SourceDeclarations['events'] = {};
  for (const sectionMember of eventsInterface.members) {
    if (!ts.isPropertySignature(sectionMember) || !sectionMember.type || !ts.isTypeLiteralNode(sectionMember.type))
      continue;
    const section = getPropertyName(sectionMember.name);
    if (!section) continue;

    const methods = (result[section] ??= {});
    for (const methodMember of sectionMember.type.members) {
      if (!ts.isPropertySignature(methodMember) || !methodMember.type || !ts.isTypeReferenceNode(methodMember.type)) {
        continue;
      }
      const method = getPropertyName(methodMember.name);
      const tuple = methodMember.type.typeArguments?.[1];
      if (!method || !tuple || !ts.isTupleTypeNode(tuple)) continue;

      const codecFields: EventFields = {};
      const nativeFields: EventFields = {};
      for (const [index, element] of tuple.elements.entries()) {
        const name = ts.isNamedTupleMember(element) ? element.name.text : String(index);
        const type = ts.isNamedTupleMember(element) ? element.type : element;
        codecFields[name] = type.getText(sourceFile);
        nativeFields[name] = translator.translateField(name, type);
      }
      methods[method] = { codecFields, nativeFields };
    }
  }
  return { events: result };
}

function findEventsInterface(sourceFile: ts.SourceFile): ts.InterfaceDeclaration | undefined {
  let result: ts.InterfaceDeclaration | undefined;
  sourceFile.forEachChild(function visit(node) {
    if (ts.isInterfaceDeclaration(node) && node.name.text === 'AugmentedEvents') result = node;
    if (!result) node.forEachChild(visit);
  });
  return result;
}

function getPropertyName(name: ts.PropertyName): string | undefined {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) return name.text;
}

function renderNativeFields(fields: EventFields): string {
  const properties = Object.entries(fields).map(([name, type]) => `readonly ${JSON.stringify(name)}: ${type}`);
  return `{ ${properties.join('; ')} }`;
}

function pascalCase(value: string): string {
  return value.replace(/(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g, (_, _separator, character: string) => {
    return character.toUpperCase();
  });
}
