import Fs from 'node:fs/promises';
import Path from 'node:path';
import { gunzipSync } from 'node:zlib';
import * as ts from 'typescript';
import { format, resolveConfig } from 'prettier';

const outputPath = Path.join(import.meta.dirname, 'HistoricalEventSpecs.generated.ts');
const npmPackage = '@argonprotocol/mainchain';
const npmPackagePath = 'package/src/interfaces/augment-api-events.ts';
const npmDeclarationPath = 'package/lib/types/interfaces/augment-api-events.d.ts';
const npmBundleDeclarationPath = 'package/lib/index.d.ts';
const includedSections = new Set([
  'balances',
  'bitcoinLocks',
  'bitcoinUtxos',
  'blockRewards',
  'bonds',
  'chainTransfer',
  'crosschainTransfer',
  'localchainTransfer',
  'miningSlot',
  'mint',
  'operationalAccounts',
  'ownership',
  'tokenGateway',
  'transactionPayment',
  'treasury',
  'vaults',
]);

const sources = {
  100: ['0.0.25'],
  101: ['1.0.0'],
  102: ['1.0.1'],
  103: ['1.0.2'],
  104: ['1.0.3'],
  105: ['1.0.4'],
  106: ['1.0.5'],
  107: ['1.0.6', '1.0.7'],
  108: ['1.0.8'],
  109: ['1.0.9'],
  110: ['1.0.10'],
  111: ['1.0.12'],
  112: ['1.0.13'],
  113: ['1.0.14'],
  114: ['1.0.15'],
  115: ['1.0.17'],
  116: ['1.0.18', '1.1.0-rc.1'],
  117: ['1.1.0-rc.2'],
  118: ['1.1.0-rc.4'],
  119: ['1.1.0-rc.5'],
  120: ['1.1.0-rc.6'],
  121: ['1.1.0-rc.7'],
  122: ['1.1.0-rc.8'],
  123: ['1.1.0'],
  124: ['argonprotocol/mainchain@1fd3a9e9'],
  125: ['1.2.0'],
  126: ['1.3.0'],
  127: ['1.3.3'],
  128: ['1.3.5'],
  129: ['1.3.6'],
  130: ['1.3.8'],
  131: ['1.3.9'],
  132: ['1.3.10'],
  133: ['1.3.11'],
  134: ['1.3.12'],
  135: ['1.3.14'],
  136: ['1.3.15'],
  137: ['1.3.17'],
  138: ['1.3.18'],
  139: ['1.3.20'],
  140: ['1.3.21'],
  141: ['1.3.22'],
  142: ['1.3.23'],
  143: ['1.3.24'],
  144: ['1.3.25'],
  145: ['1.3.26'],
  146: ['1.3.27'],
  147: ['1.4.0'],
  148: ['1.4.1', '1.4.2'],
  149: ['1.4.2-dev.9a289267'],
  150: ['1.4.3'],
  151: ['1.4.4'],
  152: ['1.4.6'],
  153: ['1.4.7'],
  154: ['1.4.8'],
  155: ['1.4.9'],
  156: ['1.4.10'],
} as const;

type EventFields = Record<string, string>;
type EventChanges = { spec: number; section: string; method: string; fields: EventFields | null }[];

const changes: EventChanges = [];
const sourceLabels: Record<number, string> = {};
let previousDeclarations: Record<string, Record<string, EventFields[]>> = {};

for (const [rawSpecVersion, sourceVersions] of Object.entries(sources)) {
  const specVersion = Number(rawSpecVersion);
  sourceLabels[specVersion] = sourceVersions
    .map(source => (source.startsWith('argonprotocol/') ? source : `${npmPackage}@${source}`))
    .join(', ');

  const declarationsForSpec: Record<string, Record<string, EventFields[]>> = {};
  const declarationsAtSpec = await Promise.all(sourceVersions.map(readEventDeclarations));
  for (const packageDeclarations of declarationsAtSpec) {
    for (const [section, methods] of Object.entries(packageDeclarations)) {
      for (const [method, fields] of Object.entries(methods)) {
        const alternatives = ((declarationsForSpec[section] ??= {})[method] ??= []);
        if (!alternatives.some(candidate => JSON.stringify(candidate) === JSON.stringify(fields)))
          alternatives.push(fields);
      }
    }
  }

  const sections = new Set([...Object.keys(previousDeclarations), ...Object.keys(declarationsForSpec)]);
  for (const section of sections) {
    const previousMethods = previousDeclarations[section] ?? {};
    const currentMethods = declarationsForSpec[section] ?? {};
    const methods = new Set([...Object.keys(previousMethods), ...Object.keys(currentMethods)]);

    for (const method of methods) {
      const previousAlternatives = previousMethods[method] ?? [];
      const currentAlternatives = currentMethods[method] ?? [];
      if (JSON.stringify(previousAlternatives) === JSON.stringify(currentAlternatives)) continue;

      if (!currentAlternatives.length) {
        changes.push({ spec: specVersion, section, method, fields: null });
      } else {
        for (const fields of currentAlternatives) changes.push({ spec: specVersion, section, method, fields });
      }
    }
  }
  previousDeclarations = declarationsForSpec;
}

const header = `// Generated by \`yarn workspace @argonprotocol/apps-indexer generate:historical-events\`.
// Sources are immutable published @argonprotocol/mainchain packages, except spec 124,
// which was not published separately and is read from its fixed mainchain commit.
// A spec emits only event tuples changed from the preceding spec. Null fields remove an event.

`;
const output = `${header}export const historicalEventSpecSources = ${JSON.stringify(sourceLabels)} as const;

export const historicalEventChanges = ${JSON.stringify(changes)} as const;
`;
const prettierConfig = await resolveConfig(outputPath);
await Fs.writeFile(outputPath, await format(output, { ...prettierConfig, parser: 'typescript' }));

async function readEventDeclarations(source: string): Promise<Record<string, Record<string, EventFields>>> {
  const contents = source.startsWith('argonprotocol/') ? await fetchGitSource(source) : await fetchNpmSource(source);
  const sourceFile = ts.createSourceFile('augment-api-events.ts', contents, ts.ScriptTarget.Latest, true);
  const eventsInterface = findEventsInterface(sourceFile);
  if (!eventsInterface) throw new Error(`Unable to find AugmentedEvents in ${source}`);

  const result: Record<string, Record<string, EventFields>> = {};
  for (const sectionMember of eventsInterface.members) {
    if (!ts.isPropertySignature(sectionMember) || !sectionMember.type || !ts.isTypeLiteralNode(sectionMember.type))
      continue;
    const section = getPropertyName(sectionMember.name);
    if (!section || !includedSections.has(section)) continue;

    const methods = (result[section] ??= {});
    for (const methodMember of sectionMember.type.members) {
      if (!ts.isPropertySignature(methodMember) || !methodMember.type || !ts.isTypeReferenceNode(methodMember.type)) {
        continue;
      }
      const method = getPropertyName(methodMember.name);
      const tuple = methodMember.type.typeArguments?.[1];
      if (!method || !tuple || !ts.isTupleTypeNode(tuple)) continue;

      const fields: EventFields = {};
      for (const [index, element] of tuple.elements.entries()) {
        if (ts.isNamedTupleMember(element)) {
          fields[element.name.text] = element.type.getText(sourceFile);
        } else {
          fields[index] = element.getText(sourceFile);
        }
      }
      methods[method] = fields;
    }
  }
  return result;
}

async function fetchNpmSource(version: string): Promise<string> {
  const response = await fetch(`https://registry.npmjs.org/@argonprotocol/mainchain/-/mainchain-${version}.tgz`);
  if (!response.ok) throw new Error(`Unable to download ${npmPackage}@${version}: ${response.status}`);

  const archive = gunzipSync(Buffer.from(await response.arrayBuffer()));
  return (
    readTarFile(archive, npmPackagePath) ??
    readTarFile(archive, npmDeclarationPath) ??
    readTarFile(archive, npmBundleDeclarationPath) ??
    failMissingSource(version)
  );
}

async function fetchGitSource(source: string): Promise<string> {
  const commit = source.slice(source.lastIndexOf('@') + 1);
  const url = `https://raw.githubusercontent.com/argonprotocol/mainchain/${commit}/client/nodejs/src/interfaces/augment-api-events.ts`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Unable to download ${source}: ${response.status}`);
  return response.text();
}

function readTarFile(archive: Buffer, requestedPath: string): string | undefined {
  for (let offset = 0; offset < archive.length; ) {
    const name = archive
      .subarray(offset, offset + 100)
      .toString()
      .replace(/\0.*$/, '');
    if (!name) return;

    const size = Number.parseInt(
      archive
        .subarray(offset + 124, offset + 136)
        .toString()
        .replace(/\0.*$/, '')
        .trim(),
      8,
    );
    const contentsOffset = offset + 512;
    if (name === requestedPath) return archive.subarray(contentsOffset, contentsOffset + size).toString();
    offset = contentsOffset + Math.ceil(size / 512) * 512;
  }
}

function findEventsInterface(sourceFile: ts.SourceFile): ts.InterfaceDeclaration | undefined {
  let result: ts.InterfaceDeclaration | undefined;
  sourceFile.forEachChild(function visit(node) {
    if (ts.isInterfaceDeclaration(node) && node.name.text === 'AugmentedEvents') result = node;
    if (!result) node.forEachChild(visit);
  });
  return result;
}

function getPropertyName(name: ts.PropertyName): string | undefined {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) return name.text;
}

function failMissingSource(version: string): never {
  throw new Error(`${npmPackage}@${version} does not include an AugmentedEvents declaration`);
}
