---
x-workspace-config: &cli-workspace
  build:
    context: ../..
    dockerfile: nodejs.workspace.Dockerfile
    additional_contexts:
      mainchain: ../../../mainchain


services:
  miner-1-setup:
    <<: *cli-workspace
  miner-1-bidder:
    <<: *cli-workspace
  miner-2-setup:
    <<: *cli-workspace
  miner-2-bidder:
    <<: *cli-workspace
