#!/bin/bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use --silent >/dev/null 2>&1 || true

yarn typecheck
yarn run lint
yarn run eslint
if git diff --cached --name-only | grep -Eq '^(package.json|yarn.lock)$'; then
  yarn run precommit
fi
(cd src-tauri && cargo fmt --all)
